[WIP][SDK-511] New method in MapGL
2gis/MapGL-iOS pull request #18
Opened 2021-04-08 21:43 UTC by maxal9999

- FloorPlan and Map.floorPlan
- Map.padding
- GeographicalBounds.extend
- Map.setStyleState and Map.patchStyleState

2021-04-12 07:51 UTC, teanet reviewed
Желательно поправить

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/FloorPlan.swift
> +	private let onLevelChanged: (Int) -> Void
private желательно под public по уровню доступа

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/FloorPlan.swift
> +			guard newValue >= 0 && newValue < levels.count else {
self.levels тоже желательно тут и ниже, для единообразия

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/GeographicalBounds.swift
> +		return GeographicalBounds(
return self.extend(points: [point])?

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/FloorPlan.swift
> +public class FloorPlan {
комбайн с 13 iOS а мы поддерживаем с 10, нужно обмазать @available(iOS 13.0, *) как минимум

никакой документации нет, нужно класс и пропрертя публичные обмазать документацией

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +			return "\"\(key)\": \(value)"}) as Array).joined(separator: ",") +
очень тяжело читается, 
давай так перепишем
```
let dictionary = self.map { (key, value) -> String in
	"""
	"\(key)": \(value)
	"""
}.joined(separator: ",")
return  "{" + dictionary + "}"
```

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/FloorPlan.swift
> +		self.currentLevel = LiveData<String>(levels[currentLevelIndex])
нет защиты от currentLevelIndex > levels.count

2021-04-12 07:51 UTC, teanet commented on Sources/MapGL/Model/Padding.swift
> +	public var top: CGFloat = 0.0
можно еще публичный init для удобства

2021-04-12 08:33 UTC, ktoto commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +			return "\"\(key)\": \(value)"}) as Array).joined(separator: ",") +
Там ещё, выше по коду, есть `IJSOptions`,  в котором делается то же самое :)

2021-04-12 08:49 UTC, maxal9999 commented on Sources/MapGL/Model/Padding.swift
> +	public var top: CGFloat = 0.0
Сделал

2021-04-12 09:08 UTC, maxal9999 commented on Sources/MapGL/Model/FloorPlan.swift
> +public class FloorPlan {
Комбайн не нужен тут - я его уберу.

2021-04-12 09:12 UTC, teanet commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +			return "\"\(key)\": \(value)"}) as Array).joined(separator: ",") +
не, там не экранируется ключ

2021-04-12 10:41 UTC, t-artikov commented on Sources/MapGL/Model/LiveData.swift
> +public class LiveData<T> {
Мимо проходил.
LiveData - стандартный класс из Android, в iOS он будет чуждым, лучше было бы использовать то что принято на платформе/в проекте.

2021-04-12 10:48 UTC, maxal9999 commented on Sources/MapGL/Model/LiveData.swift
> +public class LiveData<T> {
Да, я сделал некий аналог класс-обертку. в iOS я нашел Observable, но он доступен только с iOS 13

2021-04-12 11:04 UTC, t-artikov commented on Sources/MapGL/Model/LiveData.swift
> +public class LiveData<T> {
Думаю тебе с Женей нужно решить, как быть - написание своего observable-типа - непустяковое дело.
Если возможности iOS 13 недоступны, то может обойтись тогда колбеками, как сделано с MapView.centerDidChange, MapView.zoomDidChange.
По сравнению с Android-овской у твоей LiveData есть недостатки, делающие использование неочевидным/опасным - 
* value можно устанавливать снаружи, нарушая инкапсуляцию (в Android против этого есть разделение на LiveData/MutableLiveData)
* нет поддержки нескольких слушателей
* нельзя задать поток срабатывания callback-a (в Android тоже нельзя, но там срабатывание передается на UI-поток, что для простых случаев годится)
* установка значения непотокобезопасная

2021-04-12 11:05 UTC, maxal9999 commented on Sources/MapGL/Model/LiveData.swift
> +public class LiveData<T> {
Понял, спасибо, буду обсуждать тогда.

2021-04-12 11:48 UTC, maxal9999 commented on Sources/MapGL/Model/LiveData.swift
> +public class LiveData<T> {
Сделаю все таки колбеками. Так лучше будет, действительно.

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/Model/FitBoundsOptions.swift
> +	public init() {}
лучше убрать init и переписать 
```
public init(considerRotation: Bool = false, padding: Padding? = nil) {
 		self.considerRotation = considerRotation
 		self.padding = padding
 	}
 ```

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/Model/FitBoundsOptions.swift
> +	public var padding: Padding?
кажется это лучше сделать через let, 
public let considerRotation: Bool
public let padding: Padding?
так как выставление этих параметров ни на что не влияет и лучше эту структуру создавать только через конструктор

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/Model/Padding.swift
> +	public init() {}
тут тоже лучше удалить init и сделать один с defaultValues

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	///Extend the bounds to include a given point.
/// [пробел] Extend the bounds to include a given point.
без пробела это некорректная документация, которая не распарсится нашей утилитой

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	public func extend(points: [CLLocationCoordinate2D]) -> GeographicalBounds {
пробел после ///

2021-04-13 04:51 UTC, teanet commented on Sources/MapGL/MapView.swift
> +		if options?.failIfMajorPerformanceCaveat == true {
я пытался понять логику, и не до конца понял, вот я хочу проверить совместимость, создам 
MapView вызову этот метод до инициализации карты, и он мне вернет true,
я создаю карту, и она по итогу не создается кажется это не ожидаемое поведение

я точно не знаю как это работает, но кажется нужно возвращать этот статус как результат инициализации карты, кажется только в этот момент мы можем точно быть уверены что у нас все корректно отработает

2021-04-13 07:08 UTC, maxal9999 commented on Sources/MapGL/Model/FitBoundsOptions.swift
> +	public init() {}
Действительно, так и правда лучше

2021-04-13 10:35 UTC, aapng requested changes

2021-04-13 10:35 UTC, aapng commented on Example/HelloSDK/HelloVC.swift
> +			if let currentLevelIndex = currentLevelIndex {
Думаю, по смыслу нужно объединить проверки у первого и второго if-а. Пишется через запятую.

2021-04-13 10:35 UTC, aapng commented on Example/HelloSDK/HelloVC.swift
> +					self?.mapFloorPlanLabel.text = "Floor plan \(currentLevelIndex) shows."
```suggestion
					self?.mapFloorPlanLabel.text = "Floor plan: \(currentLevelIndex)"
```

2021-04-13 10:35 UTC, aapng commented on Example/HelloSDK/HelloVC.swift
> +				self?.mapFloorPlanLabel.text = "Floor plan hides."
```suggestion
				self?.mapFloorPlanLabel.text = "Floor plan: hidden"
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +extension Dictionary: IJSValue where Key: ExpressibleByStringLiteral, Value: IJSValue {
А зачем `ExpressibleByStringLiteral`? Это же не используется в тексте функции.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +		window.setStyleState(\(styleState.mapValues { value in value.jsValue() }.jsValue()));
Вытащи наружу выражение в `\(...)`. Приходится вчитываться, чтобы рассмотреть суть.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +
```suggestion
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +
```suggestion
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +					  let id = data["floorPlanId"] as? String else {
Обычный отступ.
```suggestion
					let id = data["floorPlanId"] as? String else {
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	public var floorPlanChange: ((Int?) -> Void)?
Нужно называть с `DidChange` — так принято у Apple.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// Notifies of the map click event.
Неактуальная документация. Плюс нужно пояснить, что значит `nil`-аргумент функции.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	///   - style: Uuid of the style.
```suggestion
	///   - style: UUID of the style.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// Upload styles object by its id and apply it to the map.
```suggestion
	/// Upload a style object by its ID and apply it to the map.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// Sets whole map style global variables at once, any previously set variables will be reset or overriden.
```suggestion
	/// Resets all global map style variables at once. Any previously set variable will be reset.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// Patches map style global variables. Use this method if you want to change a particular variable and leave other ones intact.
```suggestion
	/// Patches global map style variables. Use this method to change a particular variable and leave others intact.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// This method also resets the map pitch and rotation to 0. But the map rotation can be saved
```suggestion
	/// This method also resets the map pitch and rotation to 0. But the map rotation can be kept
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// by option considerRotation.
```suggestion
	/// by applying the `considerRotation` option.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	///   - options: FitBounds options.
```suggestion
	///   - options: Fitting options.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +		return notSupportedReason(options: options) == nil
У нас принято писать `self` всегда.

```suggestion
		return self.notSupportedReason(options: options) == nil
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	/// Tests whether the current browser supports MapGL and returns the reason if not
```suggestion
	/// Tests whether the current browser supports MapGL and returns the reason if not.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	func js(_ js: JSBridge, mapFloorPlanShow floorPlanId: String, currentLevelIndex: Int, floorLevels: [String]) {
Естественнее назвать `js(_:showFloorPlan:...)`.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	func js(_ js: JSBridge, mapFloorPlanHide floorPlanId: String) {
Естественнее назвать `js(_:hideFloorPlan:...)`.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/FitBoundsOptions.swift
> +	/// If true the fitBounds will consider the map rotation.
```suggestion
	/// If `true` the method `fitBounds` will consider map rotation.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/FloorPlan.swift
> +			guard newValue >= 0 && newValue < self.levels.count else {
Можешь писать как `(0 ..< self.levels.count).contains(newValue)`. Плюс: `newValue` упоминается только раз.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/FloorPlan.swift
> +			self.currentLevel = self.levels[currentLevelIndex]
Тут странное место. Из сеттера обращаешься к геттеру без нужды.
```suggestion
			self.currentLevel = self.levels[newValue]
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/FloorPlan.swift
> +		onLevelChanged: @escaping (Int) -> Void
Нам нужно как-нибудь понимать, что план был скрыт?

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	public var northEast: CLLocationCoordinate2D
Неожиданно. Почему поменял для `northEast`, но не `southWest`?

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	///Extend the bounds to include a given point.
```suggestion
	/// Extend the bounds to include a given point.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	///Extend the bounds to include given points.
```suggestion
	/// Extend the bounds to include given points.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/GeographicalBounds.swift
> +		points.forEach {value in
Я честно не считаю, что использование `.forEach` имеет плюсы над `for ... in` в неленивом случае.
```suggestion
		for value in points {
```
Стоит также переименовать `value` в `point`.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/GeographicalBounds.swift
> +			northEast: CLLocationCoordinate2D(latitude: minLon, longitude: minLat),
Перепроверь эту строку и следующую.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/HTML.swift
>  		var objects = new Map();
Хочу больший отступ.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/MapSupportOptions.swift
> +	/// Causes isSupported method to return false if the performance of MapGL would be
```suggestion
	/// Causes `isSupported` to return false if performance of MapGL would be
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/Padding.swift
> +/// Padding in density independent pixels from the different sides of the map canvas.
То есть в логических точках?

```suggestion
/// Padding in points from the different sides of the map canvas.
```

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/Padding.swift
> +	public init() {}
Лишний конструктор. Нужно было сделать `= 0` значениями по умолчанию в следующем.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Model/Padding.swift
> +	public var bottom: CGFloat = 0.0
Лишняя инициализация. Конструктор всё сделает сам.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +		let dictionary = self.map { (key, value) -> String in
Имя не очень хорошее. По сути это не словарь, а ключи-значения через запятую. Переименуй в `keyValues`.

2021-04-13 10:35 UTC, aapng commented on Sources/MapGL/Extensions/JS+Extensions.swift
> +		let dictionary = self.map { (key, value) -> String in
Вот со скобками уже словарь.

2021-04-13 20:18 UTC, maxal9999 commented on Sources/MapGL/JSBridge.swift
> +					  let id = data["floorPlanId"] as? String else {
Так Xcode переносит. Это неправильно?

2021-04-13 20:29 UTC, maxal9999 commented on Sources/MapGL/Model/FloorPlan.swift
> +			self.currentLevel = self.levels[currentLevelIndex]
Действительно. Ступил

2021-04-13 20:30 UTC, maxal9999 commented on Sources/MapGL/Model/FloorPlan.swift
> +		onLevelChanged: @escaping (Int) -> Void
Нет. Если план скрыт, то это все nil

2021-04-13 20:32 UTC, maxal9999 commented on Sources/MapGL/Model/GeographicalBounds.swift
> +	public var northEast: CLLocationCoordinate2D
Тут не надо было менять. Вернул let

2021-04-13 20:35 UTC, maxal9999 commented on Sources/MapGL/Model/HTML.swift
>  		var objects = new Map();
Это же js, тут вроде так можно) Просто код и так широкий. Точно хочешь?)

2021-04-13 20:35 UTC, maxal9999 commented on Sources/MapGL/Model/GeographicalBounds.swift
> +			northEast: CLLocationCoordinate2D(latitude: minLon, longitude: minLat),
Точно! Блин

2021-04-15 19:16 UTC, aapng commented on Example/HelloSDK/HelloVC.swift
> +				self?.mapFloorPlanLabel.text = "Floor plan: \(currentLevelIndex)"
Тут лишний отступ. Не нужно стесняться, что строки сливаются. Если в общепринятом стиле есть проблемы, пусть все это видят. :)
```suggestion
			self?.mapFloorPlanLabel.text = "Floor plan: \(currentLevelIndex)"
```

2021-04-15 19:16 UTC, aapng commented on Example/HelloSDK/HelloVC.swift
> +			   self?.map.floorPlan?.currentLevelIndex == currentLevelIndex {
В новом икскоде стали странно выравнивать. Получается смесь пробелов и табов. Не буду просить это править.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +		window.patchStyleState(\(styleState.mapValues { value in value.jsValue() }.jsValue()));
Тут тоже хотелось бы сделать читаемее. На твоё уже усмотрение.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +		window.fitBounds(\(bounds.jsValue()), \((options != nil) ? options.jsValue() : "null"));
Вынеси наружу и убери лишние скобки вокруг условия.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +		window.fitBounds(\(bounds.jsValue()), \((options != nil) ? options.jsValue() : "null"));
Тут интересно. Раз вызываешь `options.jsValue`, значит `Optional<FitBoundsOptions>` тоже реализует `IJSValue`. Тогда он дожен сам превращаться в `"null"` из `nil`.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +					  let id = data["floorPlanId"] as? String else {
Это глупо, но на счету икскода. Пусть остаётся так.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +				let data = body["value"] as? [String: String?]
Тут именно `[String: String?]`, а не `[String: String]`? Может быть `null` среди значений JSON?

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/JSBridge.swift
> +				delegate.js(self, supportedReason: notSupportedReason,
В другом месте уже иначе переносишь:
```
		self._support = MapSupport(
 			notSupportedReason: notSupportedReason,
 			notSupportedWithGoodPerformanceReason: notSupportedWithGoodPerformanceReason
 		)
```
Пусть тут будет так же.

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	struct MapSupport {
На практике могут оба поля быть ненулевыми? Enum бы тут подошёл?

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	public func isSupported(options: MapSupportOptions? = nil) -> Bool? {
Не хватает документации на возвращаемое значение. Что означает `nil`?

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/MapView.swift
> +	public var floorPlanDidChange: ((Int?) -> Void)?
А почему бы нам сразу всю структуру FloorPlan не отправить?

2021-04-15 19:16 UTC, aapng commented on Sources/MapGL/Model/HTML.swift
>  		var objects = new Map();
Ага. Ещё хочу уточнить: а мы помельче try можем сделать? Интересная нам ошибка прямо откуда угодно вылетает?

2021-04-15 21:44 UTC, maxal9999 commented on Sources/MapGL/JSBridge.swift
> +		window.patchStyleState(\(styleState.mapValues { value in value.jsValue() }.jsValue()));
Да, точно. По аналогии же нужно. Как я проглядел(

2021-04-15 21:47 UTC, maxal9999 commented on Sources/MapGL/JSBridge.swift
> +		window.fitBounds(\(bounds.jsValue()), \((options != nil) ? options.jsValue() : "null"));
А, уже есть 
extension Optional: IJSValue where Wrapped: IJSValue {
Так что можно оставить просто options.jsValue()

2021-04-15 21:55 UTC, maxal9999 commented on Sources/MapGL/JSBridge.swift
> +				let data = body["value"] as? [String: String?]
Вообще, зависит от вида JSON. То есть есть возможность включения null значений. Но в нашем случае такого не должно быть, так что да, ты прав, поменяю.

2021-04-15 21:59 UTC, maxal9999 commented on Sources/MapGL/MapView.swift
> +	struct MapSupport {
Да, конечно могут. Даже больше - в основном одновременно и будут ненулевыми.

2021-04-16 03:11 UTC, teanet commented on Sources/MapGL/JSBridge.swift
> +		let styleState = styleState.mapValues { value in value.jsValue() }.jsValue()
можно просто styleState.mapValues { $0.jsValue() }.jsValue()

2021-04-16 03:11 UTC, teanet commented on Sources/MapGL/JSBridge.swift
> +		let styleState = styleState.mapValues { value in value.jsValue() }.jsValue()
можно просто styleState.mapValues { $0.jsValue() }.jsValue()

2021-04-16 03:11 UTC, teanet commented on Sources/MapGL/MapView.swift
> +		if options?.failIfMajorPerformanceCaveat == true {
этот вопрос так и остался без ответа

2021-04-16 11:16 UTC, closed without merging